# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SOAP-ISIWoK
version:      1.01
version_from: lib/SOAP/ISIWoK.pm
installdirs:  site
requires:
    SOAP::Lite:                    0.01
    XML::Simple:                   0.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
