--- #YAML:1.0
name:               SOAP-ISIWoK
version:            1.03
abstract:           search and query the ISI Web of Knowledge
author:
    - Timothy D Brody <tdb2@ecs.soton.ac.uk>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    SOAP::Lite:   0.01
    XML::LibXML:  0.01
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
